CREATE TABLE `froxlor`.`PP_ABO_TYPE` (
  `PK_ABO_ID` INT NOT NULL AUTO_INCREMENT,
  `ABO_KURZ` VARCHAR(10) NULL,
  `ABO_DESC` VARCHAR(50) NULL,
  `ABO_COSTS_MTH` DOUBLE NULL,
  `ABO_COSTS_YEAR` DOUBLE NULL,
  PRIMARY KEY (`PK_ABO_ID`))
  ENGINE = MyISAM;



  
  
