CREATE TABLE `froxlor`.`PP_ABO_TYPE` (
  `PK_ABO_ID` INT NOT NULL AUTO_INCREMENT,
  `ABO_KURZ` VARCHAR(10) NULL,
  `ABO_DESC` VARCHAR(50) NULL,
  `ABO_COSTS_MTH` DOUBLE NULL,
  `ABO_COSTS_YEAR` DOUBLE NULL,
  PRIMARY KEY (`PK_ABO_ID`))
  ENGINE = MyISAM;
CREATE TABLE `froxlor`.`PP_PAYPAL_COMPLETED_TRANSACTION` (
  `EVENT_ID` INT NOT NULL AUTO_INCREMENT,
  `TXN_ID` VARCHAR(50) NULL,
  `TXN_TYPE` VARCHAR(50) NULL,
  `STATE` VARCHAR(50) NULL,
  `PAYER_ID` VARCHAR(13) NULL,
  `PAYER_EMAIL` VARCHAR(50) NULL,
  `CLIENT_ID_INTERNAL` VARCHAR(50) NULL,
  `RECIEVER_EMAIL` VARCHAR(50) NULL,
  `AMOUNT` DOUBLE NULL,
  `RECCURING_PAYMENT_ID` VARCHAR(50) NULL,
  `TIME_CREATED` VARCHAR(50) NULL,
  `NEXT_PAYMENT_DATE` VARCHAR(50) NULL,
  PRIMARY KEY (`EVENT_ID`))
ENGINE = MyISAM;
CREATE TABLE `froxlor`.`PP_PAYPAL_NOTIFICATION` (
  `EVENT_ID` INT NOT NULL AUTO_INCREMENT,
  `TXN_ID` VARCHAR(50) NULL,
  `TXN_TYPE` VARCHAR(50) NULL,
  `STATE` VARCHAR(50) NULL,
  `PAYER_ID` VARCHAR(13) NULL,
  `PAYER_EMAIL` VARCHAR(50) NULL,
  `CLIENT_ID_INTERNAL` VARCHAR(50) NULL,
  `RECIEVER_EMAIL` VARCHAR(50) NULL,
  `AMOUNT` DOUBLE NULL,
  `RECCURING_PAYMENT_ID` VARCHAR(50) NULL,
  `TIME_CREATED` VARCHAR(50) NULL,
  `NEXT_PAYMENT_DATE` VARCHAR(50) NULL,
  PRIMARY KEY (`EVENT_ID`))
ENGINE = MyISAM;



  
  
