use froxlor;
CREATE TABLE `froxlor`.`PP_ABO_TYPE` (
  `PK_ABO_ID` INT NOT NULL AUTO_INCREMENT,
  `ABO_KURZ` VARCHAR(10) NULL,
  `ABO_DESC` VARCHAR(50) NULL,
  `ABO_COSTS_MTH` DOUBLE NULL,
  `ABO_COSTS_YEAR` DOUBLE NULL,
  PRIMARY KEY (`PK_ABO_ID`))
  ENGINE = MyISAM;
CREATE TABLE `froxlor`.`PP_PAYPAL_COMPLETED_TRANSACTION` (
  `EVENT_ID` INT NOT NULL AUTO_INCREMENT,
  `TXN_ID` VARCHAR(50) NULL,
  `TXN_TYPE` VARCHAR(50) NULL,
  `STATE` VARCHAR(50) NULL,
  `PAYER_ID` VARCHAR(13) NULL,
  `PAYER_EMAIL` VARCHAR(50) NULL,
  `CLIENT_ID_INTERNAL` VARCHAR(50) NULL,
  `RECIEVER_EMAIL` VARCHAR(50) NULL,
  `AMOUNT` DOUBLE NULL,
  `RECCURING_PAYMENT_ID` VARCHAR(50) NULL,
  `TIME_CREATED` VARCHAR(50) NULL,
  `NEXT_PAYMENT_DATE` VARCHAR(50) NULL,
  PRIMARY KEY (`EVENT_ID`))
ENGINE = MyISAM;
CREATE TABLE `froxlor`.`PP_PAYPAL_NOTIFICATION` (
  `EVENT_ID` INT NOT NULL AUTO_INCREMENT,
  `TXN_ID` VARCHAR(50) NULL,
  `TXN_TYPE` VARCHAR(50) NULL,
  `STATE` VARCHAR(50) NULL,
  `PAYER_ID` VARCHAR(13) NULL,
  `PAYER_EMAIL` VARCHAR(50) NULL,
  `CLIENT_ID_INTERNAL` VARCHAR(50) NULL,
  `RECIEVER_EMAIL` VARCHAR(50) NULL,
  `AMOUNT` DOUBLE NULL,
  `RECCURING_PAYMENT_ID` VARCHAR(50) NULL,
  `TIME_CREATED` VARCHAR(50) NULL,
  `NEXT_PAYMENT_DATE` VARCHAR(50) NULL,
  PRIMARY KEY (`EVENT_ID`))
ENGINE = MyISAM;
ALTER TABLE `froxlor`.`panel_customers` 
  ADD COLUMN `PP_ABO_TYPE` INT NULL,
  ADD COLUMN `PP_ABO_EXPIRE` DATE NULL,
  ADD COLUMN `PP_SUB_COMPLETED` TINYINT(1) NULL,
  ADD COLUMN `PP_PAYPAL_CLIENT_ID` VARCHAR(13) NULL,
  ADD INDEX `PP_ABO_TYPE_idx` (`PP_ABO_TYPE` ASC);
ALTER TABLE `froxlor`.`panel_customers` 
  ADD CONSTRAINT `PP_ABO_TYPE`
    FOREIGN KEY (`PP_ABO_TYPE`)
    REFERENCES `froxlor`.`PP_ABO_TYPE` (`PK_ABO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
CREATE VIEW vKundenabos AS
SELECT
    C.customerid AS "Kundennummer",
    C.name AS "Name",
    C.firstname AS "Vorname",
    A.ABO_KURZ AS "Abo Zeichen",
    A.ABO_DESC AS "Abo Beschreibung",
    A.ABO_COSTS_MTH AS "Abo Kosten",
    C.PP_ABO_EXPIRE AS "EXPIRE",
    C.PP_SUB_COMPLETE AS "SUBCOMPLETE",
    C.PP_PAYPAL_CLIENT_ID AS "PAYPALID"
FROM
panel_customers AS C
LEFT JOIN PP_ABO_TYPE AS A
ON PK_ABO_ID = PP_ABO_TYPE;
